### ISSUE TITLE
All operations should work like transfer and convert volumes to microliters (e.g. consolidate)

### ISSUE THREAD

**Issue by scottbecker** [autoprotocol/autoprotocol-python#127]
You made a wise decision to convert volumes to microliters in Protocol.transfer.  I think you need to do the same thing in all other methods that involve volumes as well.

For example, consolidate currently doesn't convert to microliters. Here is an example of an unexpected outcome that can happen when dealing with fractional milliliters (the last line throws an exception).

def ml(milliliters):
    """Unicode function name for creating microliter volumes"""
    return Unit(milliliters,"milliliter")

well = p.ref("tube1", cont_type="micro-2.0", storage="cold_80", discard=False).well(0)
well2 = p.ref("tube2",cont_type="micro-2.0", storage="cold_80", discard=False).well(0)

p.provision(inv["water"], well, ml(2))

p.consolidate(well,well2,[ml(0.1)])
p.consolidate(well,well2,[ml(0.2)])

#this prints out "0.3"
print well2.volume.magnitude
#this assertion fails
assert(well2.volume==ml(0.3))

The fix here could be Protocol.consolidate converting milliliters into microliters, like transfer does.

**Comment by polarpine** [comment]
Fixed by #132
