### ISSUE TITLE
[{"message":"Plate type 96-deep-kf only supports lid types [\"standard\"]"

### ISSUE THREAD

**Issue by scottbecker** [autoprotocol/autoprotocol-python#128]
line 430 in conatiner_type.py should be changed from

cover_types=["universal"]

to

cover_types=["standard"]

otherwise, you get the following error when submitting a job to transcriptic.

{"message":"Plate type 96-deep-kf only supports lid types [\"standard\"]"

**Comment by bmiles** [comment]
Fixed by #129
