### ISSUE TITLE
distribute should allow for different mix settings like transfer

### ISSUE THREAD

**Issue by scottbecker** [autoprotocol/autoprotocol-python#135]
Transfer allows for mix_vol_a and mix_vol_b to allow for different settings (e.g. repetitions, speed, mix_vol).

It seems like distribute should  have similar options if its going to allow setting both mix_before and mix_after to be set True as arguments.

**Comment by scottbecker** [comment]
I just realized that distribute currently doesn't accept a mix_after argument. It seems like it should though.

**Comment by transcripticpll** [comment]
Distribute can't mix after each "to" well dispense as it would mix the contents of each "to" well with the remaining "from" well volume. 

If you want to mix the last well that you want to dispense to, I'd recommend adding a separate mix step at the end.

Alternatively, if you do want to mix between all your "to" wells, you can use:

```
transfer([A, B, C D], [B, C, D, E], [vol*4, vol*3, vol*2, vol], one_source=False, one_tip=True, **mix_kwargs)
```

Hope this is helpful!

**Comment by scottbecker** [comment]
thanks.
