### ISSUE TITLE
Where can I run protocols expressed using this library?

### ISSUE THREAD

**Issue by urish** [autoprotocol/autoprotocol-python#197]
I was looking into running them on transcriptic.com, but all the mails sent to that domain bounce back. Is transcriptic still active? Are there any alternative platforms where I can execute these protocols?

**Comment by yangchoo** [comment]
Hi @urish, Transcriptic is still active and there has been some [changes](https://www.biospace.com/article/correction-strateos-combines-transcriptic-and-3scan-to-become-premier-drug-discovery-technology-partner-for-the-pharmaceutical-industry/) recently. 

May I know what email address were you sending to? Feel free to reach out via DM as well

**Comment by urish** [comment]
Thanks for the speedy reply and congratulations on the merger!

I tried both team@transcriptic.com (the one listed on Github) and sales@transcriptic.com, both bounced with the following message:

![image](https://user-images.githubusercontent.com/892318/59999066-b1c94180-9669-11e9-8ba6-462e329a15f7.png)

I'd love if we could DM, you can reach me on twitter [@UriShaked](https://twitter.com/UriShaked), open for DMs.

**Comment by urish** [comment]
@yangchoo what is the best channel to reach you? unfortunately, Github doesn't support DMs

**Comment by yangchoo** [comment]
I've sent you an email. The sales email should now work as well, feel free to contact us at sales@strateos.com
