### ISSUE TITLE
move LICENSE file to root directory

### ISSUE THREAD

**Issue by DerAndere1** [autoprotocol/autoprotocol-python#208]
It is recommended to put the LICENSE file into the root directory of the github repository, so that it can be identified easily / automatically.
You also may want to add short Copyright/License information in the files where none is mentioned so far.

**Comment by yangchoo** [comment]
thanks for bringing this up, and apologies for the delay. This will be addressed by #232

**Comment by DerAndere1** [comment]
PR #232 makes the situation kinda worse since the change of the copyright notice is not allowed the LICENSE. Only ok if you are the original copyright holder or have the written consent of  (all) original copyright-holder(s).
