### ISSUE TITLE
Question of protocol modularity

### ISSUE THREAD

**Issue by MattyCrowther** [autoprotocol/autoprotocol-python#329]
Hi All,
I am looking into the practicalities of implementing autoprotocol for the standardisation of protocols within our lab.
I have some initial questions, if possible.

1. I am struggling to find a good set of practical examples. Is there a place where I can see them? This could be raw JSON or python scripts.
2. I would like to modularise our protocols, perhaps by some conceptual container entity. Essentially, what I am asking is it is possible to reference sub-protocols inside higher-level protocols. For example, Protocol -> [Digestion, Assembly, Transformation -> [..,..,..]] So like a hierarchical structure of arbitrary depth.
3. Is there currently any work into the generation of robotics protocols from subsets of autoprotocol? It seems like this could potentially be promising.

Thanks in advance and much appreciated.
Matty

**Comment by aaronstrateos** [comment]
We are indeed working on this. Stay tuned for the Cirrus Workflow Builder! Until then, best way to implement reusable partial-workflows is to write very modular and abstracted code.

**Comment by MattyCrowther** [comment]
Thanks, I will look into an intermediate solution, ideally keeping the protocol modularity within the JSON data.
