### ISSUE TITLE
UV transparent plates

### ISSUE THREAD

**Issue by bmiles** [autoprotocol/autoprotocol-python#43]
I think ```96-flat-uv``` is not supported yet?

```ValueError: Unknown container type 96-flat-uv (known types=['96-flat', '96-deep', '384-flat', '384-pcr', 'micro-1.5', 'micro-2.0', '96-pcr'])```

**Comment by therzka** [comment]
Hey, I recently pushed a fix to add this... maybe you just don't have the latest version of master?
