### ISSUE TITLE
Autoprotocol is not python3 compatible. 11 unit tests fail.

### ISSUE THREAD

**Issue by ParkerJones** [autoprotocol/autoprotocol-python#51]
Autoprotocol-python is not compatible with python3:
```
$ py.test-3
[...]
11 failed, 28 passed
```
Please consider pull request https://github.com/autoprotocol/autoprotocol-python/pull/34 which fixes the failing tests and doesn't break python2.7 tests 

Many thanks.

**Comment by therzka** [comment]
merged, thanks!
