### ISSUE TITLE
Math on dimensioned quantities like volume

### ISSUE THREAD

**Issue by bmiles** [autoprotocol/autoprotocol-python#65]
Am I right in that it isn't possible to do math on on say ```"200:microliters"``` because that's just a string?

Right now I am just doing string interpolation to create the values. But it would be cool to take a volume defined by a parameter and say work out 10% of that volume, maybe something similar to https://github.com/transcriptic/quantify

**Comment by therzka** [comment]
you can't do math on "200:microliter" but you can do (limited) math on Unit(200, "microliter") 

we're currently working on expanding/overhauling that class

**Comment by bmiles** [comment]
Oh nice, thanks Tali. I should read the docs more :sweat_smile:
